language: node_js
node_js:
- '14'
branches:
  only:
    - main
deploy:
  on:
    tags: true
  tag: next
  provider: npm
  email: jrmmendes@outlook.com
  api_key:
    secure: aohyCenYNW2G4Jp5UlALKVlhp3ZaD3XvCmYG4/w5eDPQ0yScAfLASivzkwSYwRIp04uIaWyVdwbyL+vpnrhu7gpiHTS6ovPKJ0kVuVQ4sFA2x/yykE4F/suEy0p3dkzefwxv9qHODKrsvVcj2LsXbaefXkeSFGpnlruqvJTfQN0tHrqit9YOZlGMN8hjpP1/ZCa0C1vRwgha0oUymwsSEpcJEjN1FXyicFZzVr4U7S0EcRE7AOINxEOP4zt+1t61erfOXZirA5a3JuJ/1p7F81ftdqwcLzS4pengAPFDm36xur2/62SOTX5vUTvV2yY/pAAgwFlzCdeX7aciuP0JEpGUxpUI89dfIxhOvlSJFPQ57HlIVU8Qd4w5Wwim49cPTfRZIuaJLvX8X85p3ettqpRhzlDnlRJaMprlbcFMK3mkKgD7N8Er6F+pwzB5JhS6sXL5wp89lBeyQrAa5U+mPYiB78RhaZVXmO40YubJVUpbfgEGgjT8PaDLQTOKNgi6vG/G2ieBTHvzs71F4tcV/f3rpAzzbP28p8ZQgbf052rk3gbEU9EnrHzoWdylLBJTPfRbB9L5H3XIStm2auS65JV+lPrTFRERd4DtS8nnVASyOgsFfSVLjMrYbHjILfMCsZYQ9rMBgG5lkOGN/nCkBKieZ7Wc2OfVGQ/2TKal4x0=
